add_newline = true

# Prompt Format
format = """
$directory\
$git_branch\
$git_status\
$fill \ 
$nodejs\
$python\
$cmd_duration\
$line_break\
$character
"""

# Active Palette
palette = "catppuccin_mocha"

# Format Customization
[directory]
format = ' [$path]($style)[$read_only]($read_only_style) '
style = 'bold directory'
read_only_style = 'bold info'
truncation_symbol = '…/'

[fill]
symbol = '─'
style = 'accent'

[git_branch]
style = 'bold primary'

[git_status]
style = 'bold info'

[nodejs]
format = '[$symbol($version )]($style)'
version_format = '${raw}'
symbol = 'Node '
style = 'italic info'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = '${raw}'
symbol = 'Python '
style = 'italic info'

[cmd_duration]
style = 'italic info'

[character]
format = ' $symbol '
success_symbol = '[❯](bold primary)'
error_symbol = '[✖](bold info)'

# Palettes
[palettes.catppuccin_mocha]
directory = "#cba6f7" # Catppuccin Mocha mauve
primary = "#89dceb" # Catppuccin Mocha sky
info = "#f5c2e7" # Catppuccin Mocha pink
accent = "#313244" # Catppuccin Mocha surface0

[palettes.cyberpunk]
directory = "#00FFFF"  # Neon cyan for directory
primary = "#FFD700"  # Bright yellow for primary elements
info = "#FF4500"  # Red-orange for info or warnings
accent = "#404040"  # Dark gray for accent elements