add_newline = true

# Prompt Format
format = """
$directory\
$git_branch\
$git_status\
$fill \ 
$nodejs\
$python\
$cmd_duration\
$line_break\
$character
"""

# Active Palette
palette = "catppuccin_mocha"

# Format Customization
[directory]
format = ' [$path]($style)[$read_only]($read_only_style) '
style = 'bold mauve'
read_only_style = 'bold pink'
truncation_symbol = '…/'

[fill]
symbol = '─'
style = 'surface0'

[git_branch]
style = 'bold sky'

[git_status]
style = 'bold purple'

[nodejs]
format = '[$symbol($version )]($style)'
version_format = '${raw}'
symbol = 'Node '
style = 'italic purple'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format = '${raw}'
symbol = 'Python '
style = 'italic purple'

[cmd_duration]
style = 'italic purple'

[character]
format = ' $symbol '
success_symbol = '[❯](bold sky)'
error_symbol = '[✖](bold pink)'

# Palettes
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"